name: Run PlumeStakingDiamond Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Run PlumeStakingDiamond tests
        run: forge test --match-path test/PlumeStakingDiamond.t.sol -vvv
